[package]
name = "futures-retry-policies"
version = "0.1.0"
edition = "2021"
authors = ["Conrad Ludgate <conradludgate@gmail.com>"]
description = "Retriable Futures"
repository = "https://github.com/conradludgate/futures-retry-policies"
license = "MIT OR Apache-2.0"
keywords = ["async", "futures", "retry", "policy", "backoff"]
categories = ["network-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
retry-policies = "0.1.1"
chrono = "0.4"
pin-project = "1"

tokio = { version = "1", optional = true, features = ["time"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[features]
default = []

# Properly document all features on docs.rs
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
