[package]
name = "futures-retry-policies"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
retry-policies = "0.1.1"
chrono = "0.4"
pin-project = "1"

tokio = { version = "1", optional = true, features = ["time"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[features]
default = []

# Properly document all features on docs.rs
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
